// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm97HrOsRzzXH9KqLSIPQJUTyLMD0tTas',
    appId: '1:913010960227:android:d2c3c75ddf559a50a59556',
    messagingSenderId: '913010960227',
    projectId: 'push-notifications-de90b',
    storageBucket: 'push-notifications-de90b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeqRAcRvCHGQcH3pnFfKcU7KRDIoEnN6k',
    appId: '1:913010960227:ios:8d3a7b35ad6118dda59556',
    messagingSenderId: '913010960227',
    projectId: 'push-notifications-de90b',
    storageBucket: 'push-notifications-de90b.appspot.com',
    iosBundleId: 'com.example.alta',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa8euA8pufcvZSpEpJ8mkVgyVv4bbQUOw',
    appId: '1:913010960227:web:05b9d03bca672061a59556',
    messagingSenderId: '913010960227',
    projectId: 'push-notifications-de90b',
    authDomain: 'push-notifications-de90b.firebaseapp.com',
    storageBucket: 'push-notifications-de90b.appspot.com',
  );

}